name: Crystal CI Ubuntu

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:nightly

    steps:
    - uses: actions/checkout@v2

    # - name: Add wget
    #   run: apt install wget
    - name: Get Chrome installer
      # run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      uses: wei/wget@v1
      with:
        args: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Install Chrome debian package
      run: apt-get install ./google-chrome-stable_current_amd64.deb -f

    - name: Show Crystal version
      run: crystal -v

    - name: Install dependencies
      # run: shards install && shards update
      run: shards install --ignore-crystal-version && shards update --ignore-crystal-version

    - name: Show repo version
      run: scripts/version_info

    - name: Run static code analysis
      run: bin/ameba --no-color
    - name: Run tests
      run: scripts/test_always

      # run: crystal spec
    - name: Run tests (w/ junit format)
      run: scripts/test_always_junit_format

